#----------------------------------------------------------------------
# This file was generated by C:\Users\Jaichi\Documents\CE4A\ECE492A\encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

DartImage1 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAJUAAACbCAIAAADkyk5oAAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAWKSURBVHhe7d1RktsgDAbg9AK9/336"
    "1FO1zpJhWYxBIAGS+DP70h07AX0II+xmX3++Xr9eL/xYjMAr+IHQIt7V5nfaRUIomlP8TJsg"
    "NCcXGlzwQxYasvxetqQpCEIrhD+WnSC0whbbmZcNILRFWCj7QGiIsFy2g9AKIckPyxm1nI/b"
    "ZlkKglAnYW3bE4Q6zdJWNbatQaicsH3bAYSaCdt+2QY3blao4iT5gVCVWcf1Lz0UE6lCRWr+"
    "haaDUBthn19K+O/v7/RHW8cOaU+3XyDM8MI/DwmZqm6O+F0dKPqBcD2tsB8IFxNK+l1PY4TX"
    "4j6c/HGDsc7mz8AWfwnCZUNq0C+7BKZ4UXFZH07+oHG/SFjEw4p0zahi+QXCih+WM7MVuX5X"
    "++p+IJxKKOAHwqlC9TeX8atU9CgqpuqK+d0JUVRMlQtvPtfvvs22oEtHfYSkX5qCKCrWDCNh"
    "PxSFa9jip8j7oShcSTjFD4TLCGf5VSoKbJAK6k70Q1Eo6PT0VnP9UBTOJpzulxHiTpOs6Ao/"
    "FBWyZum7LfLDinQS4Tq/92bd84NruN87BrzUD4RjSJWzVvuhqJAl3OCHokKQcI8figopwm1+"
    "KCpECHf6oajgE272w4qUSbjfr0KIZ5+auir87o/J4Nmnplw4QIVfsaLAs08UQi1+KeHTNhul"
    "P6cdo8gPFcXA4NPlh4qil1CdHwi7CDX6Vfa48exTpqvUD4TELNTrB0IKoWq/ImHclMF3XSiq"
    "3ytjLS3kMzwQas+/4Jp+MwkI07Fuwy8t7Yt+ejYCKRctwWPM+MW68MnvTEJLfuFOU/0lOLRN"
    "vJUxPxCaqd8rw7+VhPYG5XCuW+0qCAO5VT9MpOb9QGg7/z4DsDWTDl9aTJxoeP6M8W0Jeujj"
    "02By0rdjCZ34HXst9ON3JqErvwMJvfmdRujQ7yhCn37nELr1O4TQs98JhM79moQmNslqt9Ks"
    "d4DSfse37P3nH2WbmzIIdB5zip/XifQgP5eEZ/n5IzzOzxnhiX51Qp3rFOf3bweC7uM57kPz"
    "r1lUDAyILacc7edgIj3dzzoh/L6eYn5+bZkV6R8Kv08EjBLC7zsCFgnh9yMC5gjhl0fAFiH8"
    "ChEwRAi/cgSsfEsC/B4jYIIQfrUI6CeEXyMCygnh146AZsJ26+l7OY6PVEsIP2oEdBJSW+84"
    "t+hdU0gIv74IaCPsaz19qPo+Us8GDfwGI1AkvL6n9P77qUN5sPVT22TlzZ8Is7/8M1UUfqwI"
    "EAmfRPkjldV6/sdbf4enC+H9j28Vf8P//jn4sSKQ+cXrH9EvHM8ZxKyTOR/s49wr+tmaZTEh"
    "/FgRCH4pYfrPBVnIar2PHOL0IvrtIoQfKwKp333mDFdHYhaOXQhZreeMXB/n3nkys9mE8GNF"
    "oJhe9aSsp2NvFrJa7yOHOL14mh4r18XmdNpFCD9WBCh+96WNICGr9ZyR6+PcyvKkOIuKL2fg"
    "x4oA3W9SXc9qvY8c4vSink/N1Sl/IoUfKwK9fuJZyGo9Z+S6OXcvIfwEItB1FZTdIBVovZtM"
    "4nRkFyH8xCIwm7BY14u1njN43Zy7nhB+whFYTCjcejeZxOnISkL4TYlAnZBy14J4m2JK6zmD"
    "1825Y3Vhc0cmHhCWM/CbGIEFhBNb7yaTOB2ZSvi+uc9pHM6lRGASIebPdWO3l/CdWK0Hn+Cn"
    "xS/clCj+H4nKcgZ+6/zeC0VCPtEJ44VvaR8oVwvHxwgSwm/PwKUQZscUr4Xw2+NHmUjvl8O7"
    "aJyltnXD8TzZ7FozC+uEadUHvz0R4BDCb49ZlpdjhNmWi4qeNCccrwcQCcMSJr7SaMBvcwQo"
    "hOk9B+TfZrD7XNIkLGZeeB91nfE6Vdb7VSSssKF+UDdwIyGFDX7q/EJp3zsj/gdNFHtTgZ1X"
    "hwAAAABJRU5ErkJggg==")

